name: CodeSweep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codesweep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run AppScan CodeSweep
      uses: HCL-TECH-SW/AppScan-CodeSweep-Actions@v1
      with:
        include_paths: "."
